BOT_TOKEN = '6019491506:AAEeXGNO_wUL5Mh9mDgrsO6iUi7DIouBWxs'
URL_GAMENEWS = 'https://stopgame.ru/news'
URL_TECHNEWS = 'https://www.gazeta.ru/tech/'
URL_GAMENEWS2 = 'https://vgtimes.ru'
URL_TECHNEWS2 = 'https://hi-news.ru/technology'